name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Trigger Build

    steps:
      - run: "echo Hello"
        name: "Remote Buid"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
